# Everything except for "NoEvent" and "UserEvent"...
#
SET(vtkObject_EventFragments
  AbortCheck
  AnimationCueTick
  Any
  Char
  Configure
  ConnectionClosed
  ConnectionCreated
  CreateTimer
  CursorChanged
  Delete
  DestroyTimer
  Disable
  DomainModified
  Enable
  EndAnimationCue
  End
  EndInteraction
  EndPick
  EndWindowLevel
  Enter
  Error
  ExecuteInformation
  Exit
  Expose
  Interaction
  KeyPress
  KeyRelease
  Leave
  LeftButtonPress
  LeftButtonRelease
  MiddleButtonPress
  MiddleButtonRelease
  Modified
  MouseMove
  MouseWheelBackward
  MouseWheelForward
  Pick
  PlacePoint
  PlaceWidget
  Progress
  PropertyModified
  Register
  Render
  RenderWindowMessage
  ResetCameraClippingRange
  ResetCamera
  ResetWindowLevel
  RightButtonPress
  RightButtonRelease
  SelectionChanged
  SetOutput
  StartAnimationCue
  Start
  StartInteraction
  StartPick
  StartWindowLevel
  Timer
  UnRegister
  Update
  UpdateInformation
  UpdateProperty
  VolumeMapperComputeGradientsEnd
  VolumeMapperComputeGradientsProgress
  VolumeMapperComputeGradientsStart
  VolumeMapperRenderEnd
  VolumeMapperRenderProgress
  VolumeMapperRenderStart
  Warning
  WidgetActivate
  WidgetModified
  WidgetValueChanged
  WindowLevel
  WrongTag
  )
